name: Mon workflow
on: [push]
jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print hello message
      run: echo "Hello

